### ISSUE TITLE
import 'cypress-mailosaur' doesn't work with Cypress 5.1.0

### ISSUE THREAD

**Issue by gustawx** [mailosaur/cypress-mailosaur#6] opened 2020-09-02 09:28 UTC
After including `import 'cypress-mailosaur'` in commands.ts file I get following error:

`Property 'mailosaurGetMessage' does not exist on type 'cy & EventEmitter'`

for following code:
`cy.mailosaurGetMessage(Cypress.env('MAILOSAUR_SERVERID')`

Cypress version 5.1.0

**Comment by hippyhorse** [comment] 2020-10-07 14:18
Just to close this out, we looked into this and were unable to reproduce using v5.1.0. If you are still experiencing this, please do contact us at support@mailosaur.com

**Closed by hippyhorse** 2020-10-07 14:18 UTC
