### ISSUE TITLE
The email is not landing in the MailoSaur inbox to perform the validation of the 6-digit code.

### ISSUE THREAD

**Issue by guilhermesousa-cwi** [mailosaur/cypress-mailosaur#63] opened 2023-10-04 18:10 UTC
This issue occurred in March 2023, and it was observed that it was a delay problem with MailoSaur.

We can see that the test failed on the first run, but on the second attempt, it passed. However, in a large part, it is failing due to this delay with MailoSaur.

![image](https://github.com/mailosaur/cypress-mailosaur/assets/118919569/51754315-56b7-45e4-a599-8966dec8f283)

Here we can see the empty inbox.

---
**ERROR:** 

No matching messages found in time. By default, only messages received in the last hour are checked (use receivedAfter to override this).

reject(new Error('No matching messages found in time. By default, only messages received in the last hour are checked (use receivedAfter to override this).'));

---

When conducting the test manually with an email from my company, the registration process and email receipt happen instantly. However, when testing with MailoSaur ([xpto@hhkbhrzy.mailosaur.net](mailto:xpto@hhkbhrzy.mailosaur.net)), I also encounter the same problem as in the automation.

I have already sent an email to support regarding the matter. I am unsure about the speed of their response, so I am providing this information through the issue.

"cypress": "12.2.0"
"cypress-mailosaur": "^2.13.0"

![image](https://github.com/mailosaur/cypress-mailosaur/assets/118919569/15ac9d67-88a3-4b9f-a1c2-18673efab171)

**Comment by jm-mailosaur** [comment] 2023-10-04 20:39
Hi there,

Our team has replied. Mailosaur doesn't delay inbound email and this issue appears to relate to the service being used to send to Mailosaur. In either case the issue isn't related to the Cypress plugin or API client and so closing this - our support team will help you through via the usual channels.

Thanks

**Closed by jm-mailosaur** 2023-10-04 20:39 UTC
